### ISSUE TITLE
Upload tries to create '.' directory when source file is in root directory

### ISSUE THREAD

**Issue by villermen** [cabify/better-crowdin#27]
With the below config:

```yml
base_branches: ['master']
base_path: language
skip_validation: ['en']
files:
  - source: editor.pot
    translation: editor.%locale%.po
```

better-crowdin will try to create a '.' directory upon uploading the source file. It tries to obtain the directory of 'editor.pot' which is '.', meaning the current directory.

I have tried prefixing the file with a slash, but that will lead to the error that the file already exists in Crowdin. 'editor.pot' exists, but '/editor.pot' does not so it will try to upload instead of update it.
